services:
  - type: web
    name: magic-crop
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SUPABASE_URL
        value: https://gwocgomtdgfqtrbuomyt.supabase.co
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd3b2Nnb210ZGdmcXRyYnVvbXl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2OTg2ODcsImV4cCI6MjA1NTI3NDY4N30.Mu2gQ3ViFdLKeLMnU4XHAlyD5WcVyfsZoaVU0bmKk9Y
